name: Ruby

on: [push, pull_request]

jobs:
  build:
    name: Test (Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2']
        rails: ['6.0.6.1', '6.1.7.1', '7.0.4.1']
        include:
          - { ruby: '2.6', rails: '5.2.8.1' }
        exclude:
          - { ruby: '2.6', rails: '7.0.4.1' }
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Build and test with Rake
      run: bundle exec rake
